spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hamstagram
    username: root
    password: 2548
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  application:
    name: Hamstagram
    
mybatis:
  mapper-locations: mappers/*Mapper.xml
